baseurl = "http://salticus.github.io/"
languageCode = "en-us"
title = "Robert's rather humble homepage"

# theme = "etch"
theme = "hugo-dead-simple"

uglyUrls = true
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true

[params]
  description = "Robert's rather humble blog"
  dark = "auto"

[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  identifier = "posts"
  url = "/posts"
[[menu.main]]
  name = "Links"
  identifier = "links"
  url = "/links"
[[menu.main]]
  name = "Slides"
  identifier = "slides"
  url = "/slides"
[[menu.main]]
  name = "Talks"
  identifier = "talks"
  url = "/talks"
