#!/bin/bash


message="${1:?Update message required}"

SITE_FOLDER="public"

echo -e "Deploying updates to GitHub..."

# Build the project.
echo -e "Building site"
hugo # if using a theme, replace with `hugo -t <YOURTHEME>`

pushd "$SITE_FOLDER"

echo -e "Comitting changes"
git add .
git commit -m "$message"

echo -e "Deploying to github"
git push origin master

popd
